### ISSUE TITLE
Need to know if we can do this when our camera is on not by taking image

### ISSUE THREAD

**Issue by arorasahil1234** [anthonykrivonos/FaceRec#1]
Need to know if we can do this when our camera is on not by taking image , if i open my camera the application recognize the image and display the required data there only.no need to take images , any suggestion how we can do that ?

**Comment by anthonykrivonos** [comment]
Ionic won't be the best tool for the job if what you want is **Live Face Recognition**. In essence, you have to be taking a video and asynchronously analyzing particular frames, which cannot be currently done with Ionic 3, to my knowledge. You can check out and tinker with _Video Capture Plus_ [here](https://ionicframework.com/docs/native/video-capture-plus/), but I don't believe it'll do what you are looking for.
